---
# network settings
headers:
    Content-Type: "application/json"
    Authorization: "Basic azI6cENoM0hoTGhIeU1xdzJaRVk2VXJYcW9NOWVVKg=="
    cache-control: "no-cache"
    Postman-Token: "b1dd33bd-212f-4042-9877-e959e3f90a59"
server_port: 8080
