---
# network settings
xarm_ip: "192.168.1.200"
rpi_ip: "192.168.1.9:"
headers:
    Content-Type: "application/json"
    Authorization: "Basic azI6cENoM0hoTGhIeU1xdzJaRVk2VXJYcW9NOWVVKg=="
    cache-control: "no-cache"
    Postman-Token: "b1dd33bd-212f-4042-9877-e959e3f90a59"
server_port: 8080 # port for fluidics server

# Pump settings
pump_settings:
  pump_num: 2
  smoothie_num: 1
  priming_steps: 30
  smoothies:
    0:
      serial_port: '/dev/ttyACM0' # serial port smoothieboard is connected to on evolver raspberry pi
      serial_baudrate: '115200'
      gcode_path: "/home/pi/gcode_files/smoothie0"
      port: 5000
  pumps:
    base_media:
      type: 'fluid' # what type of fluidic action is pump for (media input, sampling, etc)
      id: 0
      smoothie: 0
      motor_connections:
        valve_steps: 30
        valve: 'X' # connection stepper motor that controls valve is connected to (either X, Y, Z, E0, E1)
        plunger: 'Y' # connection stepper motor that plunger is connected to (either X, Y, Z, E0, E1)

    selection_media:
      type: 'fluid'
      id: 1
      smoothie: 0
      motor_connections:
        valve_steps: -30
        valve: 'Z'
        plunger: 'E'

# xarm settings
xarm_params:
  roll: 180
  pitch: 0
  yaw: 1.2
  speed: 100
  mvacc: 1000

# octoprint settings
octoprint_api_key: "0E31A9B70FAA4B839176DEE63F27727F"
base_octoprint_path: "/home/pi/OctoPrint"
octoprint_pkg_path: "/home/pi/.octoprint"
